export const TYPES = {
    DATABASE_PROVIDER: Symbol('DATABASE_PROVIDER'),
    MOVIE_REPOSITORY: Symbol('MOVIE_REPOSITORY'),
    TV_SHOW_REPOSITORY: Symbol('TV_SHOW_REPOSITORY'),
    SEED_BOX_REPOSITORY: Symbol('SEED_BOX_REPOSITORY'),
    SEED_BOX: Symbol('SEED_BOX'),
    PLUGIN_FACTORY: Symbol('PLUGIN_FACTORY'),
    PLUGIN: Symbol('PLUGIN')
};