export const TYPES = {
    DATABASE_CONTEXT: Symbol('DATABASE_CONNECTION'),
    DATABASE: Symbol('DATABASE'),
    REPOSITORY_FACTORY: Symbol('REPOSITORY_FACTORY'),
    ENTITY: Symbol('ENTITY'),
    SEED_BOX: Symbol('SEED_BOX'),
    PLUGIN_FACTORY: Symbol('PLUGIN_FACTORY'),
    TORRENT_PROVIDER: Symbol('TORRENT_PROVIDER'),
    MATCH_ENGINE: Symbol('MATCH_ENGINE'),
    TORRENT_CLIENT: Symbol('TORRENT_CLIENT'),
    MEDIA_DATABASE: Symbol('MEDIA_DATABASE')
};