export const TYPES = {
    DATABASE_CONTEXT: Symbol('DATABASE_CONNECTION'),
    DATABASE: Symbol('DATABASE'),
    REPOSITORY_FACTORY: Symbol('REPOSITORY_FACTORY'),
    ENTITY: Symbol('ENTITY'),
    SEED_BOX: Symbol('SEED_BOX'),
    PLUGIN_FACTORY: Symbol('PLUGIN_FACTORY'),
    PLUGIN: Symbol('PLUGIN'),
};